[package]
name = "ffxivsavebackup"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winnt", "psapi", "processthreadsapi"] }
syn = "2.0.79"
chrono = "0.4.38"
fs_extra = "1.3.0"
